services:
  - type: web
    name: nexus-ai
    repo: https://github.com/pkdriller0/NEXUS-AI
    branch: main
    buildCommand: npm install
    startCommand: npm start
    env: node
    plan: starter
    autoDeploy: true
    envVars:
      - key: WHATSAPP_API_KEY
        value: your-api-key-here
      - key: NODE_ENV
        value: production
      # Add any other environment variables your bot needs here
